server:
  tomcat:
    accesslog:
     enabled: true
     prefix: worker
     rename-on-rotate: true
     directory: /logs
spring:
  profiles:
    active: docker
  application:
    name: ${INSTANCE_NAME}
  rabbitmq:
    addresses: ${RABBIT_ADDRESSES}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
