server:
  port: 8381
  servlet:
    context-path: /worker
spring:
  profiles:
    active: local
  rabbitmq:
    username: guest
    password: guest
    addresses: localhost:5672
  application:
    name: worker

worker:
  notification-delay-millis: 5000
  rabbit:
    queue:
      notifications-destination: q.worker.notifications
      notifications-delay-store: q.worker.notifications-store